### ISSUE TITLE
meer dan 100% gaat stemmen

### ISSUE THREAD

**Issue by mathemaat** [D66/canvas-app#1]
Dit lijkt me niet de bedoeling:

![afbeelding](https://user-images.githubusercontent.com/17109197/36109349-6d28f704-101f-11e8-8ef0-1e87d9d11015.png)

Het gaat om een test die door een afdelingsgenoot uitgevoerd is, dus ik weet niet precies waar dit mis gegaan kan zijn.

**Comment by jschreuder** [comment]
Het is mogelijk door de wijze waarop berekend wordt. Aantal stemmers is een percentage van het aantal gesprekken. Dat is inderdaad enigszins arbitrair en maakt dit mogelijk. De gedachte erachter is dat je van de meeste mensen de vraag of ze D66 willen stemmen niet positief kan beantwoorden zonder een gesprek gevoerd te hebben.
Nemen we in overweging voor volgende versie.
